// extract ABIs and deployed contract addresses from the JSON files generated by Truffle and make them available globally for the frontend to interact with the contracts

window.loadContracts = (async function () {
  try {
    const responses = await Promise.all([ // fetch all contract JSON files in parallel
      fetch("../../build/contracts/UserRegistry.json"),
      fetch("../../build/contracts/AccessControl.json"),
      fetch("../../build/contracts/MedicalDataRegistry.json"),
      fetch("../../build/contracts/AppointmentManager.json"),
      fetch("../../build/contracts/DiagnosisAndTreatment.json")
    ]);

    const data = await Promise.all(responses.map(r => r.json()));

    window.contracts = { // store the ABI and network info for each contract in a global object
      UserRegistry: { abi: data[0].abi, networks: data[0].networks },
      AccessControl: { abi: data[1].abi, networks: data[1].networks },
      MedicalDataRegistry: { abi: data[2].abi, networks: data[2].networks },
      AppointmentManager: { abi: data[3].abi, networks: data[3].networks },
      DiagnosisAndTreatment: { abi: data[4].abi, networks: data[4].networks }
    };

    console.log("Contracts loaded:", Object.keys(window.contracts));
  } catch (err) {
    console.error("Error loading contract JSONs:", err);
  }
})();
